server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: hr-api-gateway
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://hr-worker
          predicates:
            - Path=/workers-api/**
          filters:
            - RewritePath=/workers-api(?<segment>/?.*), $\{segment}
        - id: hr-payroll
          uri: lb://hr-payroll
          predicates:
            - Path=/payroll-api/**
          filters:
            - RewritePath=/payroll-api(?<segment>/?.*), $\{segment}
        - id: hr-user
          uri: lb://hr-user
          predicates:
            - Path=/users-api/**
          filters:
            - RewritePath=/users-api(?<segment>/?.*), $\{segment}
        - id: hr-oauth
          uri: lb://hr-oauth
          predicates:
            - Path=/oauth-api/**
          filters:
            - RewritePath=/oauth-api(?<segment>/?.*), $\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
